# Generated by Django 3.0.6 on 2020-08-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=200)),
                ('y', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlmodel.Image')),
            ],
        ),
    ]
