# Generated by Django 3.0.5 on 2020-08-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cordinates',
            old_name='x',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='cordinates',
            old_name='y',
            new_name='forth',
        ),
        migrations.AddField(
            model_name='cordinates',
            name='second',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cordinates',
            name='third',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
