# Generated by Django 3.0.6 on 2020-08-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_auto_20200814_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
