# Generated by Django 3.0.6 on 2020-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0003_image_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordinates',
            name='spacial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cordinates',
            name='underline',
            field=models.BooleanField(default=False),
        ),
    ]
